---
---
backend:
  name: github
  repo: bsc-des/bsc-des.github.io
  branch: master
  site_domain: bsc-des.netlify.com

media_folder: "assets/images/uploads"

logo_url: "/assets/images/logo.svg"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Intro", name: "intro", widget: "markdown"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "HUJI", name: "huji", widget: "markdown"}
          - {label: "Bezalel", name: "bezalel", widget: "markdown"}
      - label: "Projects"
        name: "projects"
        file: "projects.html"
        fields:
          - { label: "Text", name: "text", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "contact.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages-en"
    label: "Pages English"
    files:
      - label: "Home"
        name: "home"
        file: "en/index.html"
        fields:
          - {label: "Intro", name: "intro", widget: "markdown"}
          - {label: "HUJI", name: "huji", widget: "markdown"}
          - {label: "Bezalel", name: "bezalel", widget: "markdown"}
      - label: "Projects"
        name: "projects"
        file: "en/projects.html"
        fields:
          - { label: "Text", name: "text", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "en/contact.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    label_singular: "Project" # Used in the UI
    folder: "_posts/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    # prettier-ignore
    slug: {% raw %}"{{year}}-{{month}}-{{day}}-{{slug}}"{% endraw %}
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - {
          label: "Permalink",
          name: "permalink",
          widget: "hidden",
          default: "projects/:title",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          # prettier-ignore
          options: {{ site.data.tags | jsonify }},
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "faq" # Used in routes, e.g., /admin/collections/blog
    label: "Questions" # Used in the UI
    label_singular: "Question" # Used in the UI
    folder: "_posts/faq" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: {% raw %}"{{year}}-{{month}}-{{day}}-{{slug}}"{% endraw %}
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - {
          label: "Permalink",
          name: "permalink",
          widget: "hidden",
          default: "projects/:title",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          multiple: false,
          # prettier-ignore
          options: {{ site.data.faq_categories | jsonify }},
        }
      - { label: "Body", name: "body", widget: "markdown" }
